---
title: "Archiv"
output:
  html_document:
    css: www/Kinoklub_dark.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## ProCinema - Archiv

Achtung das Archiv wird aus der Datei: .../Input/Input/Procinema/procinema.txt erstellt.\
Um das Archiv zu aktualisieren muss auf der homepage <https://procinema.ch/de/login/account/> eine neue procinema.txt Datei heruntergeladen werden. Datei muss im "Kinoklub GUi" hochgeladen werden. Damit werden die Daten konvertiert und das Archiv aktualisiert.  \
\

```{r}
df_temp <- df_Procinema|>
  arrange(desc(Datum)) |>
  mutate(Datum_display = format(Datum, "%d.%m.%Y")
         )|>
  select(Datum, Datum_display, Suisanummer, Filmtitel, Spielwochen, Besucherzahl, Besucherzahlen_ch)|>
  rename(
    "Besucher Atelierkino" = Besucherzahl,
    "Besucher Schweiz" = Besucherzahlen_ch
  )

```

```{r}
# Create the datatable with a hidden Datum column and sort by it
DT::datatable(
  df_temp,
  filter = "top",
  options = list(
    pageLength = 100,
    columnDefs = list(
      list(targets = 1, visible = TRUE), # Hide the 'Datum' column
      list(targets = 2, orderData = 0)    # Use the 'Datum' column for sorting 'Datum_display'
      )
    ),
  colnames = c(Datum = "Datum_display")
)
```
