---
title: "Erfolgsrechnung Kinoklub"
output: 
  html_document:
    css: Kinoklub_dark.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
act_date <- Sys.time()|>as.Date()
act_date <- paste0(day(act_date),".", month(act_date),".", year(act_date))
```

Bericht wurde am `r act_date` erstellt.

## Erfolg
Der Erfolg berechnet sich aus dem Gewinn der Eintritte und des Kiosks. 

```{r echo=FALSE}
df_GV_Vorfuehrung|>
  left_join(df_show,by = join_by(Datum, `Suisa Nummer`))|>
    mutate(Anfang = paste0(lubridate::hour(Anfang),":", 
                           lubridate::minute(Anfang)|>as.character()|>formatC(format = "0", width = 2)|>str_replace(SPC,"0"))
         )|>
  select(Datum, Anfang, `Suisa Nummer`, Filmtitel, `Gewinn/Verlust [CHF]`)|>
  arrange(Datum)|> 
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)))|>
  rename(`Gewinn [CHF]`=`Gewinn/Verlust [CHF]`)|>
  knitr::kable()
```

```{r echo=FALSE}
df_GV_Vorfuehrung|>
  reframe(`Total Gewinn [CHF]` = sum(`Gewinn/Verlust [CHF]`))|>
  knitr::kable()
```


## Kino Eintritte Übersicht

```{r echo=FALSE}

df_Eintritt|>  
  arrange(Datum)|> 
  select(Platzkategorie, Verkaufspreis, Anzahl, Umsatz, Zahlend)|>
  group_by(Zahlend)|>
  reframe(Anzahl = sum(Anzahl),
          Umsatz = sum(Umsatz))|>
  mutate(Zahlend = if_else(Zahlend, "Zahlend", "Gratis"))|>
  rename(`Umsatz Film [CHF]` = `Umsatz`,
         Eintritt = Zahlend)|>
  knitr::kable()

```

```{r echo=FALSE}

df_Eintritt|>
  select(Platzkategorie, Verkaufspreis, Anzahl, Umsatz)|>
  reframe(Eintritt = "Total",
          Anzahl = sum(Anzahl),
          Umsatz = sum(Umsatz))|>
  rename(`Umsatz Film [CHF]` = `Umsatz`)|>
  knitr::kable()

```


### Eintritte-Gewinn pro Vorführung

```{r echo=FALSE}
df_GV_Eintritt|>
  arrange(Datum)|> 
  rename(`Umsatz [CHF]` = Umsatz,
         `Film Gewinn [CHF]` = `Gewinn/Verlust [CHF]`
         )|>
  select(-`SUISA-Abzug [%]`, `Verleiher-Abzug [%]`,-Anfang, - `Suisa Nummer`)|>
  arrange(Datum)|> 
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)))|>
  knitr::kable()
```


```{r echo=FALSE}
df_GV_Eintritt|>
  reframe(`Umsatz [CHF]` = sum(Umsatz),
          `SUISA-Abzug [CHF]` = sum(`SUISA-Abzug [CHF]`),
          `Verleiher-Abzug [CHF]` = sum(`Verleiher-Abzug [CHF]`),
          `Film Gewinn [CHF]` = sum(`Gewinn/Verlust [CHF]`)
         )|>
  knitr::kable()

```


## Werbung
### Werbeeinnahmen
```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie == "Werbung")|>
  select(Datum, Firmennamen , Betrag)|>
  rename(`Betrag [CHF]` = Betrag)|>
  mutate(Datum = paste0(day(Datum),".",month(Datum),".",year(Datum)))|>
  knitr::kable()

```

```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie == "Werbung")|>
  reframe(`Betrag [CHF]` = sum(Betrag))|>
  knitr::kable()

```

### Werbeausgaben
```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Sonstige Ausgaben"]]|>
  filter(Kategorie == "Werbung")|>
  select(Rechnungsdatum, Bezeichnung , Firmennamen, Betrag)|>
  rename(`Betrag [CHF]` = Betrag)|>
  knitr::kable()

```

```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Sonstige Ausgaben"]]|>
  filter(Kategorie == "Werbung")|>
  reframe(`Betrag [CHF]` = sum(Betrag))|>
  knitr::kable()

```

## Kiosk

### Kiosk-Gewinn pro Vorführung 
```{r echo=FALSE}
df_GV_Kiosk|>
  arrange((Datum))|> 
  rename(`Umsatz [CHF]` = Kassiert,
         `Kiosk Gewinn [CHF]` = Gewinn)|>
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)))|>
  mutate(Anfang = paste0(lubridate::hour(Anfang),":", 
                         lubridate::minute(Anfang)|>as.character()|>formatC(format = "0", width = 2)|>
                           str_replace(SPC,"0"))
         )|>
  knitr::kable()

```


```{r echo=FALSE}
df_GV_Kiosk|>
  reframe(`Umsatz [CHF]` = sum(Kassiert),
          `Kiosk Gewinn [CHF]` = sum(Gewinn)
          )|>
  knitr::kable()

```


### Kioskausgaben
```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Kioskausgaben"]]|>
  knitr::kable()
```


## Vermietungen Ein- und Ausgaben
```{r echo=FALSE}

bind_rows(
  Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie == "Vermietung")|>
  select(Datum, Firmennamen, Betrag)|>
  rename(Bezeichnung = Firmennamen, 
         Rechnungsdatum = Datum ),
  Einnahmen_und_Ausgaben[["Sonstige Ausgaben"]]|>
  filter(Kategorie == "Vermietung")|>
  select(Rechnungsdatum, Bezeichnung, Betrag)|>
  mutate(Betrag = -Betrag)
  )|>
  rename(Datum = Rechnungsdatum)|>
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)))|>
  knitr::kable()
```


## Sonstige Ausgaben
```{r echo=FALSE}

bind_rows(
  Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie != "Vermietung")|>
  select(Datum, Firmennamen, Betrag)|>
  rename(Bezeichnung = Firmennamen, 
         Rechnungsdatum = Datum ),
  Einnahmen_und_Ausgaben[["Sonstige Ausgaben"]]|>
  filter(Kategorie != "Vermietung")|>
  select(Rechnungsdatum, Bezeichnung, Betrag)|>
  mutate(Betrag = -Betrag)
  )|>
  rename(Datum = Rechnungsdatum)|>
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)))|>
  knitr::kable()
```

## Fördergelder





\
\
\
\
\
\
