---
title: "Jahresabrechnung Kinoklub"
output: 
  html_document:
    css: Kinoklub_dark.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
act_date <- Sys.time()|>as.Date()
act_date <- paste0(lubridate::day(act_date),".", lubridate::month(act_date),".", lubridate::year(act_date))
```

Bericht wurde am `r act_date` erstellt.

## Kino Vorführungen

```{r}
df_temp <- bind_rows(
  tibble(Bezeichnung = "Einnahmen Ticketverkauf",
         df_Eintritt |>
           reframe(`Betrag [CHF]` = sum(Umsatz))),
  tibble(
    Bezeichnung = "Suisaabgaben",
    df_GV_Eintritt |>
      select(Datum, Filmtitel, `SUISA-Abzug [CHF]`) |>
      reframe(`Betrag [CHF]` = -sum(`SUISA-Abzug [CHF]`))),
  tibble(
    Bezeichnung = "Verleigerabgaben",
    df_GV_Eintritt |>
      select(Datum, Filmtitel, `Verleiher-Abzug [CHF]`) |>
      reframe(`Betrag [CHF]` = -sum(`Verleiher-Abzug [CHF]`))),
  tibble(
    Bezeichnung = "Nebenkosten",
    df_GV_Eintritt |>
      select(Datum, Filmtitel, `Sonstige Kosten`) |>
      reframe(`Betrag [CHF]` = -sum(`Sonstige Kosten`, na.rm = T)))
)  

df_temp|>
  knitr::kable()
```

```{r}
df_GV_Eintritt|>
  select(Datum, Filmtitel, `Gewinn/Verlust [CHF]`)|>
  reframe(`Betrag [CHF]` = sum(`Gewinn/Verlust [CHF]`))|>
  knitr::kable()
```


## Kiosk

```{r}
df_temp <- bind_rows(
  tibble(
    Bezeichnung = "Einnahmen aus Verkauf",
    df_Kiosk |>
      reframe(`Betrag [CHF]` = sum(Betrag)) |>
      arrange(desc(`Betrag [CHF]`))
  ),
  tibble(
    Bezeichnung = "Einkauf",
    Einnahmen_und_Ausgaben[["Ausgaben"]] |>
      filter(Kategorie == "Kiosk") |>
      reframe(`Betrag [CHF]` = -sum(Betrag))
  )
)

df_temp|>
  knitr::kable()
```

```{r}
df_temp|>
  reframe(`Betrag [CHF]` = sum(`Betrag [CHF]`))|>
  knitr::kable()

```

## Werbung

```{r echo=FALSE}
df_temp <- bind_rows(
  tibble(
    Bezeichnung = "Kinowerbeeinnahmen",
    Einnahmen_und_Ausgaben[["Einnahmen"]] |>
      filter(Kategorie == "Werbung") |>
      reframe(`Betrag [CHF]` = sum(Betrag))
  ),
  tibble(
    Bezeichnung = "Kinowerbeeinnahmen",
    Einnahmen_und_Ausgaben[["Ausgaben"]] |>
      filter(Kategorie == "Werbung") |>
      reframe(`Betrag [CHF]` = -sum(Betrag))
  )
)

df_temp|>
  knitr::kable()
```

```{r}
df_temp|>
  reframe(`Betrag [CHF]` = sum(`Betrag [CHF]`))|>
  knitr::kable()

```


## Vermietungen 

```{r echo=FALSE}
df_temp <- bind_rows(
    tibble(Bezeichnung = "Kinovermietungseinnahmen",
           Einnahmen_und_Ausgaben[["Einnahmen"]] |>
             filter(Kategorie == "Vermietung") |>
             reframe(`Betrag [CHF]` = sum(Betrag))),
    tibble(Bezeichnung = "Vermietungsausgaben",
           Einnahmen_und_Ausgaben[["Ausgaben"]] |>
             filter(Kategorie == "Vermietung") |>
             reframe(`Betrag [CHF]` = -sum(Betrag)))
)

df_temp|>
  knitr::kable()

```
```{r}
df_temp|>
  reframe(`Betrag [CHF]` = sum(`Betrag [CHF]`))|>
  knitr::kable()

```

## Sonstiges

### Einnahmen
```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie == "Sonstige Einnahmen")|>
  select(Datum, Bezeichnung,Betrag)|>
  rename(`Betrag [CHF]` = Betrag)|>
  arrange(Datum)|>   
  mutate(Datum = paste0(day(Datum),".",month(Datum),".",year(Datum)))|>
  knitr::kable()

```

```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie == "Sonstige Einnahmen")|>
  reframe(`Betrag [CHF]` = sum(Betrag))|>
  knitr::kable()

```

### Ausgaben
```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Ausgaben"]]|>
  filter(Kategorie == "Sonstige Ausgaben")|>
  select(Datum, Bezeichnung,Betrag)|>
  rename(`Betrag [CHF]` = Betrag)|>
  arrange(Datum)|>
    arrange(Datum)|>   mutate(Datum = paste0(day(Datum),".",month(Datum),".",year(Datum)))|>
  knitr::kable()

```

```{r echo=FALSE}
Einnahmen_und_Ausgaben[["Ausgaben"]]|>
  filter(Kategorie == "Sonstige Ausgaben")|>
  reframe(`Betrag [CHF]` = sum(Betrag))|>
  knitr::kable()

```

### Differenz
```{r}
(Einnahmen_und_Ausgaben[["Einnahmen"]]|>
  filter(Kategorie == "Sonstige Einnahmen")|>
  reframe(`Betrag [CHF]` = sum(Betrag))-
  Einnahmen_und_Ausgaben[["Ausgaben"]]|>
  filter(Kategorie == "Sonstige Ausgaben")|>
  reframe(`Betrag [CHF]` = sum(Betrag)))|>
  knitr::kable()

```


## Gewinn / Verlust

```{r echo=FALSE}
if(sum(df_keine_Rechnnung$`keine Verleiherrechnung`)>0) {
  writeLines("Achtung es sind noch nicht alle Filmabrechnungen vorhanden. Die Einnahmen aus dem Ticketverkauf können sich noch ändern.")
}

```

```{r}
df_temp <- tibble(
  Kategorie = c("Ticketverkauf", "Kiosk", "Werbung", "Vermietung", "Sonstiges"),
  `Betrag [CHF]` = c(
    df_GV_Eintritt |>
      select(Datum, Filmtitel, `Gewinn/Verlust [CHF]`) |>
      reframe(`Betrag [CHF]` = sum(`Gewinn/Verlust [CHF]`)) |>
      pull(),
    (
      df_Kiosk |>
        reframe(`Betrag [CHF]` = sum(Betrag)) |>
        arrange(desc(`Betrag [CHF]`)) -
        Einnahmen_und_Ausgaben[["Ausgaben"]] |>
        filter(Kategorie == "Kiosk") |>
        reframe(`Betrag [CHF]` = sum(Betrag))
    ) |>
      pull(),
    (
      Einnahmen_und_Ausgaben[["Einnahmen"]] |>
        filter(Kategorie == "Werbung") |>
        reframe(`Betrag [CHF]` = sum(Betrag)) -
        Einnahmen_und_Ausgaben[["Ausgaben"]] |>
        filter(Kategorie == "Werbung") |>
        reframe(`Betrag [CHF]` = sum(Betrag))
    ) |>
      pull(),
    (
      Einnahmen_und_Ausgaben[["Einnahmen"]] |>
        filter(Kategorie == "Vermietung") |>
        reframe(`Betrag [CHF]` = sum(Betrag)) -
        Einnahmen_und_Ausgaben[["Ausgaben"]] |>
        filter(Kategorie == "Vermietung") |>
        reframe(`Betrag [CHF]` = sum(Betrag))
    ) |>
      pull(),
    (
      Einnahmen_und_Ausgaben[["Einnahmen"]] |>
        filter(Kategorie == "Sonstige Einnahmen") |>
        reframe(`Betrag [CHF]` = sum(Betrag)) -
        Einnahmen_und_Ausgaben[["Ausgaben"]] |>
        filter(Kategorie == "Sonstige Ausgaben") |>
        reframe(`Betrag [CHF]` = sum(Betrag))
    ) |>
      pull()
  )
) 

df_temp|>
  knitr::kable()

```

```{r}
df_temp|>
  reframe("Gewinn / Verlust [CHF]" = sum(`Betrag [CHF]`))|>
  knitr::kable()
```


\
\
\
\
\
\
