---
title: "Statistik Kinoklub"
output:
  html_document:
    css: www/Kinoklub_dark.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
act_date <- Sys.time()|>as.Date()
act_date <- paste0(lubridate::day(act_date),".", lubridate::month(act_date),".", lubridate::year(act_date))

# Weekdas definition in different languages
german_weekdays <- c("Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag","Sonntag")
english_weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

# Function to convert English weekday names to German, if necessary
convert_to_german_weekdays <- function(date) {
  weekday_name <- weekdays(date, abbreviate = FALSE)
  if (weekday_name %in% english_weekdays) {
    german_weekday <- german_weekdays[match(weekday_name, english_weekdays)]
  } else {
    german_weekday <- weekday_name
  }
  return(german_weekday)
}
```

Bericht wurde am `r act_date` erstellt.

## Gewinn/Verlust aus Filmvorführung

### Gewinn/Verlust aus Filmvorführung

```{r message=FALSE, warning=FALSE}
df_temp <- df_Abrechnung|>
  arrange(desc(Datum)) |>
  mutate(Datum_display = format(Datum, "%d.%m.%Y"))|>
  select(`Event ID`, Suisanummer, Filmtitel, Datum_display, Datum, Zeit, Besucherzahl, `Umsatz [CHF]`, 
         `Eventeinnahmen [CHF]`, `Eventausgaben [CHF]`,
         `Ticketgewinn [CHF]`, `Gewinn Kioskartikel [CHF]`, `Gewinn Spezialartikel [CHF]`, `Gewinn aus Fimvorführung [CHF]`)|>
  mutate(`Ticketgewinn [CHF]` = round(`Ticketgewinn [CHF]`,2), 
         `Gewinn Kioskartikel [CHF]` = round(`Gewinn Kioskartikel [CHF]`,2), 
         `Gewinn Spezialartikel [CHF]` = round(`Gewinn Spezialartikel [CHF]`,2),
         `Gewinn aus Fimvorführung [CHF]` = round(`Gewinn aus Fimvorführung [CHF]`,2)
         )
```


```{r message=FALSE, warning=FALSE}
# Create the datatable with a hidden Datum column and sort by it
DT::datatable(
  df_temp, 
  rownames = FALSE,
  options = list(
    columnDefs = list(
      # list(targets = 3,visible = F),
      list(targets = 4, visible = FALSE),  # Hide the 'Datum' column
      list(targets = 3, orderData = 4)    # Use the 'Datum' column for sorting 'Datum_display'
      )
    ),
  colnames = c(Datum = "Datum_display")
)
```


```{r}
df_temp|>
  reframe(`Gewinn/Verlust [CHF]` = sum(`Gewinn aus Fimvorführung [CHF]`,na.rm = TRUE))|>
  knitr::kable()
```

### Durchschnitt / Median
```{r}
n <- df_temp|>
  reframe(`Anzahl Vorführungen` = n())

n|>
    knitr::kable()
```


```{r}
mean_median <- df_temp|>
  reframe(`Durchschnittlicher Gewinn pro Vorführung [CHF]` = mean(`Gewinn aus Fimvorführung [CHF]`, na.rm = T)|>round5Rappen()|>round(2),
          `Median Gewinn pro Vorführung [CHF]` = median(`Gewinn aus Fimvorführung [CHF]`, na.rm = T)|>round5Rappen()|>round(2)
          )

mean_median|>
  knitr::kable()
```

```{r include=FALSE}
start_of_year <- paste0(2023,"-01-01")|>as.Date()
end_of_year <- paste0(lubridate::year(Sys.Date()) ,"-12-31")|>as.Date()

n_days_till_now <- (start_of_year - end_of_year)
n_days_till_now <- n_days_till_now|>as.integer()|>abs()
n_days_till_now

n_days_per_year <- (365 - sommerpause)
n_days_per_year

if(is_tibble(n)) n <- n$`Anzahl Vorführungen`

shows_per_year <- floor((n/n_days_till_now)*n_days_per_year)

if(n > shows_per_year) shows_per_year <- n
```

### Wochentaganalyse
```{r }
if(nrow(df_temp)>1){
  df_temp

  timeRange <- paste0(seq(0,23,1),":00","-", seq(1,24,1),":00")

  m <- str_split(timeRange, "-")|>
    sapply(function(range){
      (df_temp$Zeit) >= hm(range[1]) & (df_temp$Zeit) < hm(range[2])
    })
  colnames(m) <- timeRange
  m

  m <- m|>
  as_tibble()|>
  pivot_longer(cols = everything(), names_to = "Time Range")|>
  filter(`value` == TRUE)
}else{
  timeRange <- paste0(seq(0,23,1),":00","-", seq(1,24,1),":00")
  m <- str_split(timeRange, "-")|>
    sapply(function(range){
      hm(df_temp$Zeit) >= hm(range[1]) & hm(df_temp$Zeit) < hm(range[2])
    })

  m <- tibble(
    `Time Range` = timeRange,
    value = m
    )
}
```

```{r}
df_temp <- m|>
  filter(`value` == TRUE)|>
  bind_cols(df_temp)|>
  select(-value)|>
  mutate(
    weekday = sapply(Datum, convert_to_german_weekdays),
    weekday = factor(weekday, levels = german_weekdays)
  ) |>
  group_by(weekday, `Time Range`)|>
  reframe(d_gewinn = sum(`Gewinn aus Fimvorführung [CHF]`) / n(),
          d_gewinn = round5Rappen(d_gewinn)
          )|>
  mutate(`Time Range` = factor(`Time Range`, levels = timeRange[length(timeRange):1])
         )
```

```{r fig.width=10}
df_temp|>
  mutate(`Time Range` = factor(`Time Range`, levels(`Time Range`)))|>
  ggplot(aes(weekday, `Time Range`))+
  geom_point(size = 20, color = "grey30" )+
  geom_text(aes(label = d_gewinn), color = "darkorange2")+
  labs(title = "Durchschnittlicher Gewinn / Verlust",
       subtitle = "[CHF]",
       x = "Wochentag", y = "Zeit-Interval"
       )+
  my_template
```

