---
title: "Statistik Kinoklub"
output:
  html_document:
    css: Kinoklub_dark.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
act_date <- Sys.time()|>as.Date()
act_date <- paste0(day(act_date),".", month(act_date),".", year(act_date))
```

Bericht wurde am `r act_date` erstellt.

## Statistik

### Eintritte

```{r fig.width=12}
df_Eintritt|>
  group_by(Platzkategorie, Zahlend)|>
  reframe(Anzahl = sum(Anzahl))|>
  arrange(Anzahl)|>
  mutate(Platzkategorie = factor(Platzkategorie, levels = Platzkategorie))|>
  ggplot(aes(Platzkategorie,Anzahl, fill =  Zahlend))+
  geom_col()+
  #labs(title = "Anzahl Eintritte")+
  coord_flip()+
  theme_bw()+
  theme(
  panel.background = element_rect(fill = "#322f3b",
                                colour = "#322f3b",
                                size = 0.5, linetype = "solid"),
  plot.background = element_rect(fill = "#322f3b"),
  axis.title = element_text(colour = "#f4cccc", size =15),
  axis.text= element_text(colour = "#f4cccc"),
  title = element_text(colour = "#f4cccc", size = 20),
  legend.position = c(.95, .25),
  legend.justification = c("right", "top"),
  legend.box.just = "right",
  legend.margin = margin(6, 6, 6, 6),
  legend.background = element_rect(fill = "#322f3b", color = "black"),
  legend.text = element_text(color = "#f4cccc")
  
  )
```

```{r }
df_Eintritt|>
  group_by(Platzkategorie)|>
  reframe(Anzahl = sum(Anzahl),
          `Film Umsatz [CHF]` = sum(Umsatz))|>
    arrange(desc(`Film Umsatz [CHF]`))|>
  knitr::kable()

```

```{r}
df_Eintritt|>
  reframe(`Film Umsatz [CHF]` = sum(Umsatz))|>
  knitr::kable()
```


```{r }
df_Eintritt|>
  select(Platzkategorie, Verkaufspreis, Anzahl, Umsatz, Zahlend)|>
  group_by(Zahlend)|>
  reframe(Anzahl = sum(Anzahl))|>
  mutate(Zahlend = if_else(Zahlend, "Zahlend", "Gratis"))|>
  rename(Eintritt = Zahlend)|>
  knitr::kable()

```





### Filmabgaben
```{r echo=FALSE}
df_GV_Eintritt|>
  select(Datum, Anfang, Filmtitel, Umsatz, `SUISA-Abzug [CHF]`,`Verleiher-Abzug [CHF]`)|>
  arrange(Datum)|>
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)),
         Anfang = paste0(lubridate::hour(Anfang),":", lubridate::minute(Anfang)|>as.character()|>formatC(format = "0", width = 2)|>str_replace(SPC,"0")))|>
  knitr::kable()

df_GV_Eintritt|>
  reframe(`Abgabe and die SUISA [CHF]` = sum(`SUISA-Abzug [CHF]`),
          `Abgaben and den Verleiger [CHF]` = sum(`Verleiher-Abzug [CHF]`)
          )|>
  knitr::kable()

```

## Kiosk 

### Verkaufsartikel 
```{r }
df_temp <- df_Kiosk|>
  select(-Betrag)|>
  group_by(Verkaufsartikel)|>
  reframe(Anzahl = sum(Anzahl), 
          `Umsatz [CHF]` = sum(Kassiert),
          `Gewinn [CHF]` = sum(Gewinn)
          )|>
  arrange(desc(Anzahl))

```


```{r }
# library(flextable)
flextable::set_flextable_defaults(background.color = "#322f3b", 
                       font.color = "#f4cccc")


flextable::flextable(df_temp)|>
  flextable::autofit(add_w = 1.5)|>
  flextable::set_table_properties(opts_html = list(scroll = list( height = "500px",
                                                                  width = "150px",
                                                                  freeze_first_column = TRUE )))
```



```{r }
df_temp <- df_Kiosk|>
  reframe(`Verkaufsartikel` = NA,
          `Anzahl verkaufter Verkaufsartikel` = sum(Anzahl),
          `Umsatz Kiosk [CHF]` = sum(Kassiert),
          `Gewinn Kiosk [CHF]` = sum(Gewinn) ,
          )|>
  arrange(desc(`Anzahl verkaufter Verkaufsartikel`))


df_temp|>
  flextable::flextable()|>
  flextable::autofit(add_w = 1.5)|>
  flextable::set_table_properties(opts_html = list( scroll = list(height = "100px",
                                                                  width = "180px",
                                                                  freeze_first_column = TRUE)
                                                    )
                                  )

```

### Ladenhüter (keine Verkäufe)
```{r }

df_temp <- df_Einkaufspreise|>
  distinct(`Artikelname Kassensystem`)|>
  left_join(df_Kiosk|>
            group_by(Verkaufsartikel)|>
              reframe(Anzahl = sum(Anzahl)),
            by = c("Artikelname Kassensystem"="Verkaufsartikel")
            )
  
df_temp|>
  filter(is.na(Anzahl))|>
  select(-Anzahl)|>
  knitr::kable()

```
### Kiosk Umsatz pro Gast

```{r }
df_temp <- df_show |>
  left_join(
    df_Eintritt |>
      group_by(Datum) |>
      reframe(`Besucher` = sum(Anzahl))|>
      left_join(df_Kiosk |>
                  group_by(Datum) |>
                  reframe(Umsatz = sum(Kassiert)),
                by = join_by(Datum)
                ) |>
      mutate(`Umsatz pro Gast [CHF]` = (Umsatz / `Besucher`) |> round(2)),
  by = join_by(Datum)
  )|>
  select(-Ende, -Saal, -Version, -Alter)|>
  filter(!is.na(`Suisa Nummer`))|>
  rename(`Umsatz [CHF]` = Umsatz)|>
  arrange(desc(Datum))|>
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)),
         Anfang = paste0(lubridate::hour(Anfang),":", lubridate::minute(Anfang)|>as.character()|>formatC(format = "0", width = 2)|>str_replace(SPC,"0")))
```


```{r }
df_temp|>
  knitr::kable()

df_temp|>
  reframe(`Umsatz pro Gast [CHF]` = sum(`Umsatz [CHF]`)/sum(Besucher))|>
  knitr::kable()

```


### Kiosk Umsatz pro zahlender Gast
```{r }
df_temp <- df_show |>
  left_join(
    df_Eintritt |>
      filter(Zahlend)|>
      group_by(Datum) |>
      reframe(`Besucher` = sum(Anzahl))|>
      left_join(df_Kiosk |>
                  group_by(Datum) |>
                  reframe(Umsatz = sum(Kassiert)),
                by = join_by(Datum)
                ) |>
      mutate(`Umsatz pro Gast [CHF]` = (Umsatz / `Besucher`) |> round(2)),
  by = join_by(Datum)
  )|>
  arrange(desc(Datum))|>
  mutate(Datum = paste0(lubridate::day(Datum),".", lubridate::month(Datum),".", lubridate::year(Datum)),
         Anfang = paste0(lubridate::hour(Anfang),":", lubridate::minute(Anfang)|>as.character()|>formatC(format = "0", width = 2)|>str_replace(SPC,"0")))|>
  select(-Ende, -Saal, -Version, -Alter)|>
  filter(!is.na(`Suisa Nummer`))|>
  rename(`Umsatz [CHF]`= Umsatz)
```


```{r }
df_temp|>
  knitr::kable()

df_temp|>
  reframe(`Umsatz pro Gast [CHF]` = sum(`Umsatz [CHF]`)/sum(Besucher))|>
  knitr::kable()
```

