---
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
act_date <- Sys.time()|>as.Date()
act_date <- paste0(day(act_date),".", month(act_date),".", year(act_date))

```

```{r variablen, include=FALSE}
ii <- 1
```


```{r echo=FALSE}
c_verteilprodukt <- df_Abrechnung|>
  filter(Datum == df_mapping$Datum[ii],
         `Suisa Nummer` == df_mapping$Suisanummer[ii] )|>
  select(Verteilprodukt)|>
  pull()

c_Datum <- df_Abrechnung|>
  filter(Datum == df_mapping$Datum[ii],
         `Suisa Nummer` == df_mapping$Suisanummer[ii] )|>
  select(Datum)|>
  pull()

c_linkDatum <- df_Abrechnung|>
  filter(Datum == df_mapping$Datum[ii],
         `Suisa Nummer` == df_mapping$Suisanummer[ii] )|>
   select(`Link Datum`)|>
   pull()

c_suisa <- df_Abrechnung|>
  filter(Datum == df_mapping$Datum[ii],
         `Suisa Nummer` == df_mapping$Suisanummer[ii] )|>
  select(`Suisa Nummer`)|>
  rename(Suisanummer = `Suisa Nummer`)|>
  pull()
  

```


<!-- ```{r include=FALSE} -->
<!-- df_mapping <- tibble(Datum = c_Date)|> -->
<!--   mutate(user_Datum = paste0(day(Datum),".", month(Datum),".", year(Datum)), -->
<!--          index = row_number()) -->

<!-- c_Datum <- c_Date[ii] -->

<!-- c_linkDatum <- df_Abrechnung|> -->
<!--   filter(Datum == c_Date[ii])|> -->
<!--    select(`Link Datum`)|> -->
<!--    pull() -->

<!-- c_suisa <- df_show|> -->
<!--   filter(Datum == c_Date[ii])|> -->
<!--   select(`Suisa Nummer`)|> -->
<!--   pull() -->

<!-- ``` -->


\

**TaB* AtelierKino** \
Tunaustrasse 5 \
5734 Reinach \
\


```{r}
df_temp <- df_verleiherabgaben|>
  filter(Datum %in% c(c_Datum, c_linkDatum),
         Suisanummer == c_suisa
         )
```

`r df_temp$Verleiher[1]` \
`r df_temp$Adresse[1]` \
`r df_temp$PLZ[1]` `r df_temp$Ort[1]` \
\
\
Reinach , `r act_date` 
\
\


## Verleiherabrechnung
```{r}
df_temp1 <- df_show|>
  filter(Datum %in% c(c_Datum, c_linkDatum))|>
  select(`Suisa Nummer`, Filmtitel, Datum, Anfang, Ende, Saal)|>
  mutate(Anfang = paste0(lubridate::hour(Anfang),":", lubridate::minute(Anfang)|>as.character()|>formatC(format = "0", width = 2)|>str_replace(rebus::SPC,"0")),
         Ende = paste0(lubridate::hour(Ende),":", lubridate::minute(Ende)|>as.character()|>formatC(format = "0", width = 2)|>str_replace(rebus::SPC,"0")),
         Datum = paste0(day(Datum),".",month(Datum),".",year(Datum))
         )

df_temp1|>
  knitr::kable()
```

### Eintritte und Umsatz
```{r}
df_temp <- df_Abrechnung|>
  filter(Datum %in%c(c_Datum))
```


```{r}
c_suisa_prozent <- df_temp|>
  distinct(`SUISA-Vorabzug [%]`)|>
  pull()

df_temp <- df_Abrechnung_tickes|>
  filter(Datum %in%c(c_Datum, c_linkDatum),
         )

```


```{r}
df_temp <- df_temp|>
  slice(1:(nrow(df_temp)/2))|>
  select(Datum, Platzkategorie, `Verkaufspreis [CHF]`, Anzahl,`Verkaufspreis Abgerechnet [CHF]`,`Umsatz für Netto3 [CHF]`)|>
  rename(`Umsatz [CHF]` = `Umsatz für Netto3 [CHF]`)|>
  mutate(Datum = paste0(day(Datum),".",month(Datum),".",year(Datum))
         )

```


```{r}
df_temp1 <- df_temp|>
  group_by(Platzkategorie)|>
  reframe(Anzahl = sum(Anzahl),
          `Umsatz [CHF]` = sum(`Umsatz [CHF]`))

```


```{r}
df_temp1 <- df_temp|>
  distinct(Platzkategorie, .keep_all = T)|>
  select(Platzkategorie, `Verkaufspreis Abgerechnet [CHF]`)|>
  left_join(df_temp1,
            by = join_by(Platzkategorie))|>
  arrange(desc(`Umsatz [CHF]`))

```


```{r}
df_temp1|>
  knitr::kable()
```


```{r}
Brutto <- df_temp|>
  reframe(`Brutto [CHF]` = sum(`Umsatz [CHF]`, na.rm = T))
```


```{r}
df_temp <- Brutto|>
  mutate(Brutto = Brutto|>pull(),
         Tax = 0,
         `Netto 1 [CHF]` = `Brutto [CHF]`,
         `Netto 0.00%` = 0,
         `Netto 2 [CHF]` = `Brutto [CHF]`,
         `SUISA-Vorabzug [CHF]` = (`Brutto [CHF]` * c_suisa_prozent/100)|>round5Rappen()
         )

df_temp|>
  select(-`Brutto [CHF]`)|>
  t()|>
  knitr::kable()
```


```{r}
df_temp|>
  mutate(`Netto 3 [CHF]` = (`Brutto [CHF]` - `SUISA-Vorabzug [CHF]`))|>
  select(`Netto 3 [CHF]`)|>
  knitr::kable()
```

